/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prepaquiz4;

import javax.swing.JOptionPane;

/**
 *
 * @author anton
 */
public class Ventana extends javax.swing.JFrame {
    static Lista l1;
    static Lista l2;
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        l1= new Lista();
        l2= new Lista();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l1add = new javax.swing.JButton();
        l2add = new javax.swing.JButton();
        Comparar = new javax.swing.JButton();
        Lista1 = new javax.swing.JTextField();
        Lista2 = new javax.swing.JTextField();
        VerLista1 = new javax.swing.JTextField();
        VerLista2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Resultado = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1add.setText("Add");
        l1add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1addActionPerformed(evt);
            }
        });
        jPanel1.add(l1add, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 158, 78, -1));

        l2add.setText("Add");
        l2add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l2addActionPerformed(evt);
            }
        });
        jPanel1.add(l2add, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 158, 78, -1));

        Comparar.setText("Comparar");
        Comparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompararActionPerformed(evt);
            }
        });
        jPanel1.add(Comparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 223, 109, -1));
        jPanel1.add(Lista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 223, 121, -1));
        jPanel1.add(Lista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 223, 121, -1));

        VerLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerLista1ActionPerformed(evt);
            }
        });
        jPanel1.add(VerLista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 84, 121, -1));

        VerLista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerLista2ActionPerformed(evt);
            }
        });
        jPanel1.add(VerLista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 84, 129, -1));

        jLabel1.setText("Lista 1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 49, 113, 23));

        jLabel2.setText("Lista 2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 52, 111, -1));

        jLabel3.setText("Resultado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 292, 85, -1));
        jPanel1.add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 289, 188, -1));

        jButton4.setText("Rest");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 252, 78, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l1addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1addActionPerformed
        try{
            l1.Begin(Integer.parseInt(Lista1.getText()));
            VerLista1.setText(l1.recorrer());
            Lista1.setText("");
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error debe ingresar un numero");
        }
    }//GEN-LAST:event_l1addActionPerformed

    private void VerLista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerLista2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerLista2ActionPerformed

    private void CompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompararActionPerformed
        
        if (l2.comparar(l1)==true && l1.comparar(l2)==true) {
            Resultado.setText("las lista son iguales");
        }else{
            if (l1.isEmpty() && l2.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Error no se puede comparar lista vacia"); 
            }else{
                Resultado.setText("Las lista no son iguales");
            }
    }
    }//GEN-LAST:event_CompararActionPerformed

    private void VerLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerLista1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerLista1ActionPerformed

    private void l2addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l2addActionPerformed
        try{
            l2.Begin(Integer.parseInt(Lista2.getText()));
            VerLista2.setText(l2.recorrer());
            Lista2.setText("");
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error debe ingresar un numero");
        }
    }//GEN-LAST:event_l2addActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        l1.Empty();
        l2.Empty();
        VerLista1.setText("");
        VerLista2.setText("");
        Resultado.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comparar;
    private javax.swing.JTextField Lista1;
    private javax.swing.JTextField Lista2;
    private javax.swing.JTextField Resultado;
    private javax.swing.JTextField VerLista1;
    private javax.swing.JTextField VerLista2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton l1add;
    private javax.swing.JButton l2add;
    // End of variables declaration//GEN-END:variables
}
