/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package antony_cen_quiz1;

import javax.swing.JOptionPane;

/**
 *
 * @author sl001
 */
public class Interfaz extends javax.swing.JFrame {
    public Lista Ls1;
    public Lista Ls2;
    public Solucion com;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        Ls1=new Lista("Mi lista1");
        Ls2=new Lista("Mi lista2");
        com=new Solucion(Ls1,Ls2);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextoL1 = new javax.swing.JTextField();
        TextoL2 = new javax.swing.JTextField();
        add1 = new javax.swing.JButton();
        add2 = new javax.swing.JButton();
        InputL1 = new javax.swing.JTextField();
        InputL2 = new javax.swing.JTextField();
        Igual = new javax.swing.JTextField();
        Comparar = new javax.swing.JButton();
        Rest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Lista 1:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 60, -1));

        jLabel2.setText("Lista 2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));
        jPanel1.add(TextoL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, -1));
        jPanel1.add(TextoL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 110, -1));

        add1.setText("Agregar L1");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });
        jPanel1.add(add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 113, 110, 30));

        add2.setText("Agregar L2");
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });
        jPanel1.add(add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 100, 30));
        jPanel1.add(InputL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, -1));
        jPanel1.add(InputL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 153, 110, 30));
        jPanel1.add(Igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 150, 30));

        Comparar.setText("Comparar");
        Comparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompararActionPerformed(evt);
            }
        });
        jPanel1.add(Comparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        Rest.setText("Reset");
        Rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestActionPerformed(evt);
            }
        });
        jPanel1.add(Rest, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
        try{
            this.Ls2.Insertar(Integer.parseInt(InputL2.getText()), this.Ls2.Final());
            this.TextoL2.setText(Ls2.Recorrer());
            this.InputL2.setText("");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error debe ingresar un numero !");
        }
    }//GEN-LAST:event_add2ActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        try{
            this.Ls1.Insertar(Integer.parseInt(InputL1.getText()), this.Ls1.Final());
            this.TextoL1.setText(Ls1.Recorrer());
            this.InputL1.setText("");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error debe ingresar un numero !");
        }
    }//GEN-LAST:event_add1ActionPerformed

    private void RestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestActionPerformed
        try{
            if (!Ls1.EsVacio() || Ls2.EsVacio()) {
                Ls1.VaciarLista();
                Ls2.VaciarLista();
                InputL1.setText("");
                InputL2.setText("");
                TextoL1.setText("");
                TextoL2.setText("");
                Igual.setText("");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No tiene nada en las dos Lista");
        }
        
    }//GEN-LAST:event_RestActionPerformed

    private void CompararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompararActionPerformed
        
        if (com.Comparar(Ls1)==true && com.Comparar(Ls2)==true) {
            Igual.setText("Las listas son iguales");
        }else{
             if (Ls1.EsVacio() && Ls2.EsVacio()) {
                JOptionPane.showMessageDialog(null, "La lista esta Vacias");
            }else{
                 Igual.setText("Las lista no son iguales");
             }
         }
         
    }//GEN-LAST:event_CompararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comparar;
    private javax.swing.JTextField Igual;
    private javax.swing.JTextField InputL1;
    private javax.swing.JTextField InputL2;
    private javax.swing.JButton Rest;
    private javax.swing.JTextField TextoL1;
    private javax.swing.JTextField TextoL2;
    private javax.swing.JButton add1;
    private javax.swing.JButton add2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
