
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ANTONY
 */
public class Interfaz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());
    Solucion sol=new Solucion();
    public String cadena;
    
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        sol.OriginalTree.insertRoot(50);
        sol.OriginalTree.insertLeft(50, 26);
        sol.OriginalTree.insertRight(50, 96);
        sol.OriginalTree.insertLeft(26, 86);
        sol.OriginalTree.insertRight(26, 4);
        sol.OriginalTree.insertLeft(86,100);
        sol.OriginalTree.insertRight(4, 24);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PosABB = new javax.swing.JTextField();
        PreOrdenBB = new javax.swing.JLabel();
        PreBB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InBB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PosBB = new javax.swing.JTextField();
        PreABB = new javax.swing.JTextField();
        InABB = new javax.swing.JTextField();
        Convertir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        InsertarR = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        InsertarIzq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PosOrden ABB:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, 30));

        PosABB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosABBActionPerformed(evt);
            }
        });
        jPanel1.add(PosABB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 280, 30));

        PreOrdenBB.setText("PreOrden BB:");
        jPanel1.add(PreOrdenBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 30));

        PreBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreBBActionPerformed(evt);
            }
        });
        jPanel1.add(PreBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 33, 280, 30));

        jLabel3.setText("InOrden BB:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 30));

        InBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InBBActionPerformed(evt);
            }
        });
        jPanel1.add(InBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 280, 30));

        jLabel4.setText("PosOrden BB:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 30));

        jLabel5.setText("PreOrden ABB:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 30));

        jLabel6.setText("InOrden ABB:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        PosBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosBBActionPerformed(evt);
            }
        });
        jPanel1.add(PosBB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 280, 30));

        PreABB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreABBActionPerformed(evt);
            }
        });
        jPanel1.add(PreABB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 280, 30));

        InABB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InABBActionPerformed(evt);
            }
        });
        jPanel1.add(InABB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 280, 30));

        Convertir.setText("Convertir");
        Convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertirActionPerformed(evt);
            }
        });
        jPanel1.add(Convertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 120, -1));

        jButton2.setText("Rest");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 120, -1));

        InsertarR.setText("Agregar Raiz");
        InsertarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarRActionPerformed(evt);
            }
        });
        jPanel1.add(InsertarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, -1));

        jButton1.setText("Agregar Derecho");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 140, -1));

        InsertarIzq.setText("Agregar Izquierdo");
        InsertarIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarIzqActionPerformed(evt);
            }
        });
        jPanel1.add(InsertarIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PosABBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosABBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PosABBActionPerformed

    private void PreBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreBBActionPerformed

    private void InBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InBBActionPerformed

    private void PosBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PosBBActionPerformed

    private void PreABBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreABBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PreABBActionPerformed

    private void InABBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InABBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InABBActionPerformed

    private void ConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertirActionPerformed
        // TODO add your handling code here:
        if (sol.OriginalTree.its_empty(sol.OriginalTree.root)) {
            JOptionPane.showMessageDialog(this, "El arbol esta vacio");
        }
        PreBB.setText(sol.OriginalTree.PreOrden(sol.OriginalTree.getRoot()));
        InBB.setText(sol.OriginalTree.InOrden(sol.OriginalTree.getRoot()));
        PosBB.setText(sol.OriginalTree.InOrden(sol.OriginalTree.getRoot()));
        sol.convertToBST();
        PreABB.setText(sol.NewTree.PreOrden(sol.NewTree.getRoot()));
        InABB.setText(sol.NewTree.InOrden(sol.NewTree.getRoot()));
        PosABB.setText(sol.NewTree.PosOrden(sol.NewTree.getRoot()));
        
        
        
        
    }//GEN-LAST:event_ConvertirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        sol.OriginalTree.vaciar();
        sol.NewTree.vaciar();
        PreBB.setText("");
        InBB.setText("");
        PosBB.setText("");
        PreABB.setText("");
        InABB.setText("");
        PosABB.setText("");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void InsertarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarRActionPerformed
        // TODO add your handling code here:
        if (sol.OriginalTree.root!=null) {
            JOptionPane.showMessageDialog(this, "Ya tiene raiz");
        }else{
            sol.OriginalTree.insertRoot(Integer.parseInt(JOptionPane.showInputDialog("Ingrese La Raiz: ")));
        }
        
        
    }//GEN-LAST:event_InsertarRActionPerformed

    private void InsertarIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarIzqActionPerformed
        // TODO add your handling code here:
        if (sol.OriginalTree.root!=null) {
            sol.OriginalTree.insertLeft(Integer.parseInt(JOptionPane.showInputDialog("Ingrese el padre: ")), 
                    Integer.parseInt(JOptionPane.showInputDialog("Ingrese el hijo: ")));
        }else{
            sol.OriginalTree.insertRoot(Integer.parseInt(JOptionPane.showInputDialog("Ingrese La Raiz: ")));
        }
        
        
    }//GEN-LAST:event_InsertarIzqActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (sol.OriginalTree.root!=null) {
            sol.OriginalTree.insertRight(Integer.parseInt(JOptionPane.showInputDialog("Ingrese el padre: ")), 
                    Integer.parseInt(JOptionPane.showInputDialog("Ingrese el hijo: ")));
        }else{
            sol.OriginalTree.insertRoot(Integer.parseInt(JOptionPane.showInputDialog("Ingrese La Raiz: ")));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Convertir;
    private javax.swing.JTextField InABB;
    private javax.swing.JTextField InBB;
    private javax.swing.JButton InsertarIzq;
    private javax.swing.JButton InsertarR;
    private javax.swing.JTextField PosABB;
    private javax.swing.JTextField PosBB;
    private javax.swing.JTextField PreABB;
    private javax.swing.JTextField PreBB;
    private javax.swing.JLabel PreOrdenBB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
