/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praticaparcial1;

import javax.swing.JOptionPane;

/**
 *
 * @author anton
 */
public class Ventana extends javax.swing.JFrame {
    public static Lista list1;
    public static Lista list2;
    public static Solucion sol;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        this.list1=new Lista();
        this.list2=new Lista();
        this.sol=new Solucion();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lista1 = new javax.swing.JTextField();
        lista2 = new javax.swing.JTextField();
        Add1 = new javax.swing.JButton();
        Add2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Resultado = new javax.swing.JTextField();
        Encontrar1 = new javax.swing.JButton();
        Encontrar2 = new javax.swing.JButton();
        l2 = new javax.swing.JTextField();
        l1 = new javax.swing.JTextField();
        rest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Encontrar una lista");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 140, 30));

        lista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista1ActionPerformed(evt);
            }
        });
        jPanel1.add(lista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, -1));

        lista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista2ActionPerformed(evt);
            }
        });
        jPanel1.add(lista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 130, -1));

        Add1.setText("Agregar L1");
        Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add1ActionPerformed(evt);
            }
        });
        jPanel1.add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        Add2.setText("Agregar L2");
        Add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add2ActionPerformed(evt);
            }
        });
        jPanel1.add(Add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jLabel3.setText("List2:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, 30));

        jLabel4.setText("List1:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 30));
        jPanel1.add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 110, -1));

        Encontrar1.setText("Encontrar 1");
        Encontrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Encontrar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Encontrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        Encontrar2.setText("Encontrar 2");
        Encontrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Encontrar2ActionPerformed(evt);
            }
        });
        jPanel1.add(Encontrar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 130, -1));
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, -1));

        rest.setText("Rest");
        rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restActionPerformed(evt);
            }
        });
        jPanel1.add(rest, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add1ActionPerformed
        try{
            this.list1.Append(Integer.parseInt(lista1.getText()));
            //System.out.println(list1.pFirst.getData());
            l1.setText(list1.Recorrer());
            lista1.setText("");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_Add1ActionPerformed

    private void Add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add2ActionPerformed
        try{
            this.list2.Append(Integer.parseInt(lista2.getText()));
            //System.out.println(list1.pFirst.getData());
            l2.setText(list2.Recorrer());
            lista2.setText("");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_Add2ActionPerformed

    private void lista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lista1ActionPerformed

    private void lista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lista2ActionPerformed

    private void Encontrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Encontrar1ActionPerformed
        try{
            Resultado.setText(Integer.toString(sol.EncuentroSublista1(list1, list2)));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
    }//GEN-LAST:event_Encontrar1ActionPerformed

    private void Encontrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Encontrar2ActionPerformed
        try{
            Resultado.setText(Integer.toString(sol.EncuentroSublista2(list1, list2)));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
    }//GEN-LAST:event_Encontrar2ActionPerformed

    private void restActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restActionPerformed
        try{
            if (!list1.isEmpty()) {
                this.list1.Vaciar();
                this.list2.Vaciar();
                this.Resultado.setText("");
                this.lista1.setText("");
                this.lista2.setText("");
                this.l1.setText("");
                this.l2.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Las listas estan vacias");
            }
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_restActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add1;
    private javax.swing.JButton Add2;
    private javax.swing.JButton Encontrar1;
    private javax.swing.JButton Encontrar2;
    private javax.swing.JTextField Resultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField l1;
    private javax.swing.JTextField l2;
    private javax.swing.JTextField lista1;
    private javax.swing.JTextField lista2;
    private javax.swing.JButton rest;
    // End of variables declaration//GEN-END:variables
}
