/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizpractica.Interfaces;

import javax.swing.JOptionPane;
import quizpractica.EDD.Lista;


/**
 *
 * @author valeriazampetti
 */
public class InterfazdePlaylist extends javax.swing.JFrame {
    static Lista lista;
    static String cancionabuscar ;

    /**
     * Creates new form InterfazdePlaylist
     */
    public InterfazdePlaylist(Lista lista) {
        this.lista= lista;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FieldBuscarCancion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InputTextFielDeArtista = new javax.swing.JTextField();
        MostrarPlaylist = new javax.swing.JButton();
        BuscarPorNombreDeCancion = new javax.swing.JButton();
        FiltrarPorArtista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel1.setText("Buscar Cancion por el nombre de la cancion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        FieldBuscarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldBuscarCancionActionPerformed(evt);
            }
        });
        getContentPane().add(FieldBuscarCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, -1));

        jLabel2.setText("Filtrar cancion por el nombre del artista");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        InputTextFielDeArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTextFielDeArtistaActionPerformed(evt);
            }
        });
        getContentPane().add(InputTextFielDeArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, -1));

        MostrarPlaylist.setText("Mostrar Playlist");
        MostrarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarPlaylistActionPerformed(evt);
            }
        });
        getContentPane().add(MostrarPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        BuscarPorNombreDeCancion.setText("Buscar");
        BuscarPorNombreDeCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPorNombreDeCancionActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarPorNombreDeCancion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        FiltrarPorArtista.setText("Filtrar");
        FiltrarPorArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrarPorArtistaActionPerformed(evt);
            }
        });
        getContentPane().add(FiltrarPorArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldBuscarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldBuscarCancionActionPerformed
        // TODO add your handling code here:
        cancionabuscar= FieldBuscarCancion.getText();

    }//GEN-LAST:event_FieldBuscarCancionActionPerformed

    private void MostrarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPlaylistActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, lista.RetornarCanciones() );

    }//GEN-LAST:event_MostrarPlaylistActionPerformed

    private void BuscarPorNombreDeCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPorNombreDeCancionActionPerformed
        // TODO add your handling code here:
        String cancion = FieldBuscarCancion.getText();

        JOptionPane.showMessageDialog(this, lista.BuscarCancion(cancion));

    }//GEN-LAST:event_BuscarPorNombreDeCancionActionPerformed

    private void FiltrarPorArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrarPorArtistaActionPerformed
        // TODO add your handling code here:
        String artista = InputTextFielDeArtista.getText();
        Lista listafiltrada=  lista.FiltrarArtista(artista);
        JOptionPane.showMessageDialog(this, listafiltrada.RetornarCanciones() );
    }//GEN-LAST:event_FiltrarPorArtistaActionPerformed

    private void InputTextFielDeArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTextFielDeArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputTextFielDeArtistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazdePlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazdePlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazdePlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazdePlaylist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazdePlaylist(lista).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarPorNombreDeCancion;
    private javax.swing.JTextField FieldBuscarCancion;
    private javax.swing.JButton FiltrarPorArtista;
    private javax.swing.JTextField InputTextFielDeArtista;
    private javax.swing.JButton MostrarPlaylist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
